name: "Build"

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches:
    #   - master


jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2.3.3
    
    - name: Setup NuGet
      uses: actions/setup-dotnet@v1.7.2
      
    - name: Restore NuGet packages
      run:  nuget restore autodarts-visual.sln
      
    - name: Setup MSBuild and Build the solution
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build solution autodarts-visual.sln
      run:  msbuild autodarts-visual.sln /p:platform="Any CPU" /p:Configuration='Release'
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: WPFApp-GitHubActionsActions
        path: "autodarts-visual/bin/Release"