name: "Build"

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches:
    #   - master


jobs:
  build:

    runs-on: windows-latest

    timeout-minutes: 10

    env:
        Solution_Path: autodarts-visual.sln
        Project_Path: autodarts-visual\autodarts-visual.csproj
        Release_Path: autodarts-visual\bin\Release
        # TestProject_Path: src\WpfApp1\WpfApp1Test\WpfApp1Test.csproj
        # NUnitConsole_Path: src\WpfApp1\packages\NUnit.ConsoleRunner.3.15.0\tools\nunit3-console.exe
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1

    - name: Nuget Restore
      run: nuget restore ${{ env.Solution_Path }}
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    # - name: Create the test Dll  
    #   run: msbuild ${{ env.TestProject_Path }} -t:rebuild -property:Configuration=Debug
    
    # - name: Nunit Test
    #   run: ${{ env.NUnitConsole_Path }} ${{ env.TestProject_Path }}
    
    - name: Create the app Exe  
      run: msbuild ${{ env.Project_Path }} -t:rebuild -property:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
          name: Release
          path: ${{ env.Release_Path }}