name: "Build"

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches:
    #   - master


env:
    PROJECT_PATH: autodarts-visual/autodarts-visual.csproj
  
  jobs:
    deploy:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
  
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
  
        - run: dotnet restore ${{ env.PROJECT_PATH }}
  
        - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
  
        - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true
  
        - uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
  
        - uses: csexton/release-asset-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pattern: autodarts-visual/bin/Release/net6.0-windows10.0.22621.0/win-x64/publish/*.exe
            release-url: ${{ steps.create_release.outputs.upload_url }}